advanced-topics.Rmd:
  path: dev/advanced-topics.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/a-non-mathematician-s-introduction-to-monads.Rmd
  inflate:
    flat_file: dev/advanced-topics.Rmd
    vignette_name: A non-mathematician's introduction to monads
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_bind_fmap.Rmd:
  path: dev/flat_bind_fmap.Rmd
  state: active
  R: R/bind_record.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_bind_fmap.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_chronicle.Rmd:
  path: dev/flat_chronicle.Rmd
  state: active
  R: R/record.R
  tests: tests/testthat/test-record.R
  vignettes: []
  inflate:
    flat_file: dev/flat_chronicle.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_data_doc.Rmd:
  path: dev/flat_data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_ggplot.Rmd:
  path: dev/flat_ggplot.Rmd
  state: active
  R: R/ggplot_fun.R
  tests: tests/testthat/test-ggplot_fun.R
  vignettes: []
  inflate:
    flat_file: dev/flat_ggplot.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_named_args.Rmd:
  path: dev/flat_named_args.Rmd
  state: active
  R: []
  tests: tests/testthat/test-named_args.R
  vignettes: []
  inflate:
    flat_file: dev/flat_named_args.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_pipe.Rmd:
  path: dev/flat_pipe.Rmd
  state: active
  R: R/pipe.R
  tests: tests/testthat/test-pipe.R
  vignettes: []
  inflate:
    flat_file: dev/flat_pipe.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_purely.Rmd:
  path: dev/flat_purely.Rmd
  state: active
  R: R/purely.R
  tests: tests/testthat/test-purely.R
  vignettes: []
  inflate:
    flat_file: dev/flat_purely.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
flat_zzz.Rmd:
  path: dev/flat_zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
maybe-monad.Rmd:
  path: dev/maybe-monad.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/the-maybe-monad.Rmd
  inflate:
    flat_file: dev/maybe-monad.Rmd
    vignette_name: The Maybe monad
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
real-world-example.Rmd:
  path: dev/real-world-example.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/a-real-world-example.Rmd
  inflate:
    flat_file: dev/real-world-example.Rmd
    vignette_name: A real world example
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
z-save_avia.Rmd:
  path: dev/z-save_avia.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/developer-vignette-including-the-avia-data-to-the-package.Rmd
  inflate:
    flat_file: dev/z-save_avia.Rmd
    vignette_name: 'Developer Vignette: Including the avia data to the package'
    open_vignette: true
    check: false
    document: true
    overwrite: 'yes'
