---
title: "Purely"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```


```{r function-purely}
#' Capture all errors, warnings and messages.
#' @param .f A function to decorate.
#' @param strict Controls if the decorated function should catch only errors (1), errors and
#'   warnings (2, the default) or errors, warnings and messages (3).
#' @return A function which returns a list. The first element of the list, `$value`,
#' is the result of the original function `.f` applied to its inputs. The second element, `$log` is
#' `NULL` in case everything goes well. In case of error/warning/message, `$value` is NA and `$log`
#' holds the message. `purely()` is used by `record()` to allow the latter to handle errors.
#' @importFrom rlang try_fetch eval_tidy cnd_message
#' @importFrom maybe just nothing is_nothing
#' @examples
#' purely(log)(10)
#' purely(log)(-10)
#' purely(log, strict = 1)(-10) # This produces a warning, so with strict = 1 nothing gets captured.
#' @export
purely <- function(.f, strict = 2){

  function(..., .log_df = "Log start..."){

    if(any(purrr::map_lgl(list(...), maybe::is_nothing))){
    
          final_result <- list(
            value = maybe::nothing(),
            log_df = "A `Nothing` was given as input."
          )
    
    } else {

      res <- switch(strict,
                    only_errors(.f, ...),
                    errors_and_warnings(.f, ...),
                    errs_warn_mess(.f, ...))

      final_result <- list(
        value = NULL,
        log_df = NULL
      )

      final_result$value <- if(any(c("error", "warning", "message") %in% class(res))){
                              maybe::nothing()
                            } else {
                              maybe::just(res)
                            }

      final_result$log_df <- if(any(c("error", "warning", "message") %in% class(res))){
                               rlang::cnd_message(res)
                             } else {
                               NA
                             }


    }

    final_result

  }
}



#' @noRd
only_errors <- function(.f, ...){

  rlang::try_fetch(
           rlang::eval_tidy(.f(...)),
           error = function(err) err,
           )

}

#' @noRd
errors_and_warnings <- function(.f, ...){

  rlang::try_fetch(
           rlang::eval_tidy(.f(...)),
           error = function(err) err,
           warning = function(warn) warn,
           )
}

#' @noRd
errs_warn_mess <- function(.f, ...){

  rlang::try_fetch(
           rlang::eval_tidy(.f(...)),
           error = function(err) err,
           warning = function(warn) warn,
           message = function(message) message,
           )
}
```

```{r tests-purely}
test_that("purely decorated function provides correct result", {
  expect_equal((purely(log)(10))$value, maybe::just(log(10)))
})


test_that("purely decorated function provides right result", {
  expect_equal((purely(log)(seq(1, 10)))$value, maybe::just(log(seq(1, 10))))
})

test_that("purely decorated function provides NA if problem", {
  expect_equal((purely(log)(-10))$value, maybe::nothing())
})

test_that("purely decorated function log", {
  expect_type((purely(log)(-10))$log_df, "character")
})

test_that("compose purely decorated functions", {

  pure_sqrt <- purely(sqrt)
  pure_mean <- purely(mean)
  pure_exp <- purely(exp)

  result_pipe <- 1:10 |>
    pure_sqrt() %>=%
    pure_exp() %>=%
    pure_mean()

  expect_equal(result_pipe$value, maybe::just(mean(exp(sqrt(1:10)))))

})


test_that("compose purely decorated dplyr functions on data.frame", {

  pure_select <- purely(dplyr::select)
  pure_filter <- purely(dplyr::filter)
  pure_summarise <- purely(dplyr::summarise)

  result_pure <- mtcars |>
    pure_select(am, starts_with("c")) %>=%
    pure_filter(am == 1) %>=%
    pure_summarise(mean_cyl = mean(cyl))

  result_impure <- mtcars |>
    dplyr::select(am, starts_with("c")) |>
    dplyr::filter(am == 1) |>
    dplyr::summarise(mean_cyl = mean(cyl))

  expect_equal(result_pure$value, maybe::just(result_impure))

})


test_that("compose purely decorated dplyr functions on tibbles", {

  pure_select <- purely(dplyr::select)
  pure_filter <- purely(dplyr::filter)
  pure_summarise <- purely(dplyr::summarise)

  result_pure <- mtcars |>
    tibble::as_tibble() |>
    pure_select(am, starts_with("c")) %>=%
    pure_filter(am == 1) %>=%
    pure_summarise(mean_cyl = mean(cyl))

  result_impure <- mtcars |>
    tibble::as_tibble() |>
    dplyr::select(am, starts_with("c")) |>
    dplyr::filter(am == 1) |>
    dplyr::summarise(mean_cyl = mean(cyl))

  expect_equal(result_pure$value, maybe::just(result_impure))

})


test_that("test group_by", {

  pure_group_by <- purely(dplyr::group_by)

  expect_equal(maybe::just(dplyr::group_by(mtcars, carb)), pure_group_by(mtcars, carb)$value)

})
```
