---
title: "Forward pipe"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r function-pipe, filename = "pipe.R"}
#' Pipe a chronicle object to a decorated function.
#' @param .c A value returned by record.
#' @param .f A chronicle function to apply to the returning value of .c.
#' @return A chronicle object.
#' @importFrom rlang enquo quo_get_expr quo_get_env call_match call2 eval_tidy
#' @importFrom maybe from_maybe nothing
#' @examples
#' r_sqrt <- record(sqrt)
#' r_exp <- record(exp)
#' 3 |> r_sqrt() %>=% r_exp()
#' @export
`%>=%` <- function(.c, .f) {

  f_quo <- rlang::enquo(.f)
  f_exp <- rlang::quo_get_expr(f_quo)
  f_env <- rlang::quo_get_env(f_quo)
  f_chr <- deparse(f_exp[[1]])

  f <- get(f_chr, envir = f_env)

  q_ex_std <- rlang::call_match(call = f_exp, fn = f)
  expr_ls <- as.list(q_ex_std)

  # need to set .value to empty, if not .value will be matched multiple times in call2
  names(expr_ls)[names(expr_ls) == ".value"] <- ""

  rlang::eval_tidy(rlang::call2(f,
                                .value = maybe::from_maybe(.c$value, default = maybe::nothing()),
                                !!!expr_ls[-1],
                                .log_df = .c$log_df))

}

```

```{r tests-pipe, filename = "pipe.R"}
test_that("errors get captured and logs composed", {

  r_sqrt <- record(sqrt)
  r_mean <- record(mean)
  r_exp <- record(exp)

  result_pipe <- -1:-10 |>
    r_mean() %>=%
    r_sqrt() %>=%
    r_exp()

  expect_equal(nrow(result_pipe$log_df), 3)

})


test_that("test that pipe and bind_loud give same results", {

  r_sqrt <- record(sqrt)
  r_mean <- record(mean)
  r_exp <- record(exp)

  result_pipe <- 1:10 |>
    r_sqrt() %>=%
    r_exp() %>=%
    r_mean()

  result_bind <- 1:10 |>
    r_sqrt() |>
    bind_record(r_exp) |>
    bind_record(r_mean)

  expect_equal(result_pipe$value, result_bind$value)

})


test_that("test that pipe and bind_loud give same results for dplyr functions", {

  r_select <- record(dplyr::select)
  r_filter <- record(dplyr::filter)
  r_group_by <- record(dplyr::group_by)
  r_summarise <- record(dplyr::summarise)

  result_pipe <- mtcars |>
    as_chronicle() %>=%
    r_select(am, starts_with("c")) %>=%
    r_filter(am == 1) %>=%
    r_group_by(carb) %>=%
    r_summarise(mean_cyl = mean(cyl))

  result_bind <- mtcars |>
    as_chronicle() |>
    bind_record(r_select, am, starts_with("c")) |>
    bind_record(r_filter, am == 1) |>
    bind_record(r_group_by, carb) |>
    bind_record(r_summarise, mean_cyl = mean(cyl))

  expect_equal(result_pipe$value, result_bind$value)

})


```
