# WARNING - Generated by {fusen} from dev/flat_named_args.Rmd: do not edit by hand

test_that("purely decorated function with named args works", {

  pmean <- purely(mean)

  arg <- c(1, 2, 3)

  expect_equal(pmean(arg), pmean(x = arg))

})


test_that("purely decorated function, we can name many arguments", {

  soma <- function(x, y){

    res <- x+y
  
    return(res)
  }
  
  psoma <- purely(soma)
  
  expect_equal(psoma(2, 6), psoma(2, y = 6))

  expect_equal(psoma(2, 6), psoma(x = 2, y = 6))
  
})


test_that("record decorated function with named args works", {

  rmean <- record(mean)

  arg <- c(1, 2, 3)

  expect_equal(rmean(arg)$value, rmean(x = arg)$value)

})


test_that("record decorated function, we can name many arguments", {

  soma <- function(x, y){

    res <- x+y
  
    return(res)
  }
  
  rsoma <- record(soma)
  
  expect_equal(rsoma(2, 6)$value, rsoma(2, y = 6)$value)

  expect_equal(rsoma(2, 6)$value, rsoma(x = 2, y = 6)$value)
    
})

