# WARNING - Generated by {fusen} from dev/flat_chronicle.Rmd: do not edit by hand

test_that("first and only error message is ok", {

  r_select <- record(dplyr::select)

  result_pipe <- mtcars |>
    r_select(bm)


  expect_true(grepl("Can't select columns that don't exist", result_pipe$log_df$message))

})


test_that("if multiple error messages, next ones are 'pipe failed'", {

  r_select <- record(dplyr::select)
  r_filter <- record(dplyr::filter)
  r_mutate <- record(dplyr::mutate)

  result_pipe <- mtcars |>
    r_select(bm) %>=%
    r_filter(bm == 1) %>=%
    r_mutate(bm = 3)


  expect_true(grepl("Can't select columns that don't exist", result_pipe$log_df$message[1]))
  expect_true(grepl("Pipeline failed upstream", result_pipe$log_df$message[2]))
  expect_true(grepl("Pipeline failed upstream", result_pipe$log_df$message[3]))

})

testthat::test_that("test check_g", {

  r_select <- record(dplyr::select, .g = dim)

  result_pipe <- mtcars |>
    r_select(am)

  expected_result <- tibble::tribble(~ops_number, ~`function`, ~g,
                                     1, "dplyr::select", c(32, 1)
                                     ) |> as.data.frame()

  expect_equal(expected_result, check_g(result_pipe))

})

test_that("test running time", {

  sleeping <- function(x, y = 0){

    Sys.sleep(x)
    x + y

  }

  r_sleep <- record(sleeping)

  result_pipe <- r_sleep(1) %>=%
    r_sleep(2)

  expect_equal(sum(as.integer(result_pipe$log_df$run_time)), 2)
})
