# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]

name: style-with-air

permissions: write-all

jobs:
  style_pkg:
    runs-on: ubuntu-latest
    env:
     GH_TOKEN: ${{ github.token }}
     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Create this folder to silence warning
        run: mkdir -p ~/.nix-defexpr/channels

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Run Air
        run: nix-shell --quiet -p air-formatter --run "air format ."

      - name: config bot user and check for changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git diff-index --quiet HEAD || echo "has_changes=true" >> $GITHUB_ENV

      - name: commit if changes
        if: env.has_changes == 'true'
        run: |
          git add \*.R
          git add \*.Rmd
          git commit -m 'Style via air'

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
